# Generated by Django 5.0.1 on 2024-03-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_par', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tee_Time',
            fields=[
                ('tee_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_size', models.IntegerField()),
                ('tee_date_time', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tee_Time_Group_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.person')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tee_time')),
            ],
        ),
    ]
